### ISSUE TITLE
[BUG] 계좌 조회 api 변경 필요

### ISSUE THREAD

**Issue by Leehyeonju0219** [PDA-ARMAGYETDON/pda-armagyetdon-backend#88]
### 버그 요약

프론트에서 account_id를 알 수 없으므로, 계좌 조회를 할 수 없다.

### 재현 단계

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/1ba7d83c-4d47-4c87-a167-5a6e634f7c58">

- 계좌 조회 시, 현재 account_id를 엔드포인트에 넣어서 호출해야하는데 프론트에서는 account_id를 알 방법이 없다. 
- 따라서 개인 계좌 조회, 모임 계좌 조회 api를 각각 따로 만들어서 
    - 개인 계좌 조회 시, 액세스 토큰의 user_id로 계좌를 조회하여 리턴하고,
    - 모임 계좌 조회 시, 액세스 토큰의 team_id로 계좌를 조회하여 리턴하도록 해야할 것 같습니다.

### 예상 결과

개인 계좌 조회와 모임 계좌 조회 시, 각각 다른 api를 요청하여 원하는 결과를 반환해줄 수 있다.

### 실제 결과

- `GET` api/accounts/personal
- `GET` api/accounts/team
이렇게 두 개로 api를 분리해야할 것 같습니다.

### 심각도

높음

**Comment by Elandland** [comment]
개인 계좌 내용을 조회할 일은 없어서 안만들고 
![image](https://github.com/user-attachments/assets/1cf00aea-3334-492a-a6c6-d47dc0d278ed)
accountController단에 teamId를 통해 해당 계좌의 보유 종목 및 자산, data가져오는 api새로 작성했습니다.
 기존 개인계좌 조회, 모임 계좌 조회는 개발 단계에서 사용하기 위해 유지시켰습니다.
